### PR TITLE
fix: Missing ssl_mode in variable read_replicas.ip_configuration

### PR DESCRIPTION
**Pull request by strimpak**

### CODE REVIEW

**Comment by strimpak** [comment]
I figured out that there was another point that ssl_mode was missing.

@isaurabhuttam , @imrannayer could you please review?

**Comment by strimpak** [comment]
I fixed a lint failure: [update modules/mysql/README.md with make generate_docs](https://github.com/terraform-google-modules/terraform-google-sql-db/pull/638/commits/a78eb1890e390ab694d4fae76b94408fe1cd84a3)

**Comment by imrannayer** [comment]
@strimpak thx for the PR. Can u plz fix lint issues?

**Comment by strimpak** [comment]
@imrannayer I have fixed them

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
