### PR TITLE
feat: Add ```deny_maintenance_period``` for MySQL, MsSQL, PostgreSQL and safer_sql

### PR DESCRIPTION
**Pull request by aniketkumarj**
Added the ```deny_maintenance_period``` with fields ```end_date```, ```start_date``` and ```time``` for different databases i.e MySQL, MsSQL, PostgreSQL and safer_sql to fix the following issue: [#391](https://github.com/terraform-google-modules/terraform-google-sql-db/issues/391)

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./modules/mysql/main.tf:92:      } 
./modules/postgresql/main.tf:86:      } 
./modules/mssql/main.tf:81:      } 
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/mysql/main.tf
--- old/modules/mysql/main.tf
+++ new/modules/mysql/main.tf
@@ -86,10 +86,10 @@
     dynamic "deny_maintenance_period" {
       for_each = var.deny_maintenance_period
       content {
-        end_date   = lookup(deny_maintenance_period.value, "end_date" , null)
-        start_date = lookup(deny_maintenance_period.value, "start_date" , null)
-        time       = lookup(deny_maintenance_period.value, "time" , null)
-      } 
+        end_date   = lookup(deny_maintenance_period.value, "end_date", null)
+        start_date = lookup(deny_maintenance_period.value, "start_date", null)
+        time       = lookup(deny_maintenance_period.value, "time", null)
+      }
     }
     dynamic "ip_configuration" {
       for_each = [local.ip_configurations[local.ip_configuration_enabled ? "enabled" : "disabled"]]
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/postgresql/main.tf
--- old/modules/postgresql/main.tf
+++ new/modules/postgresql/main.tf
@@ -80,10 +80,10 @@
     dynamic "deny_maintenance_period" {
       for_each = var.deny_maintenance_period
       content {
-        end_date   = lookup(deny_maintenance_period.value, "end_date" , null)
-        start_date = lookup(deny_maintenance_period.value, "start_date" , null)
-        time       = lookup(deny_maintenance_period.value, "time" , null)
-      } 
+        end_date   = lookup(deny_maintenance_period.value, "end_date", null)
+        start_date = lookup(deny_maintenance_period.value, "start_date", null)
+        time       = lookup(deny_maintenance_period.value, "time", null)
+      }
     }
     dynamic "ip_configuration" {
       for_each = [local.ip_configurations[local.ip_configuration_enabled ? "enabled" : "disabled"]]
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/mssql/main.tf
--- old/modules/mssql/main.tf
+++ new/modules/mssql/main.tf
@@ -75,10 +75,10 @@
     dynamic "deny_maintenance_period" {
       for_each = var.deny_maintenance_period
       content {
-        end_date   = lookup(deny_maintenance_period.value, "end_date" , null)
-        start_date = lookup(deny_maintenance_period.value, "start_date" , null)
-        time       = lookup(deny_maintenance_period.value, "time" , null)
-      } 
+        end_date   = lookup(deny_maintenance_period.value, "end_date", null)
+        start_date = lookup(deny_maintenance_period.value, "start_date", null)
+        time       = lookup(deny_maintenance_period.value, "time", null)
+      }
     }
     dynamic "ip_configuration" {
       for_each = [local.ip_configurations[local.ip_configuration_enabled ? "enabled" : "disabled"]]
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./modules/mysql/main.tf:92:      } 
./modules/postgresql/main.tf:86:      } 
./modules/mssql/main.tf:81:      } 
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/mysql/main.tf
--- old/modules/mysql/main.tf
+++ new/modules/mysql/main.tf
@@ -86,10 +86,10 @@
     dynamic "deny_maintenance_period" {
       for_each = var.deny_maintenance_period
       content {
-        end_date   = lookup(deny_maintenance_period.value, "end_date" , null)
-        start_date = lookup(deny_maintenance_period.value, "start_date" , null)
-        time       = lookup(deny_maintenance_period.value, "time" , null)
-      } 
+        end_date   = lookup(deny_maintenance_period.value, "end_date", null)
+        start_date = lookup(deny_maintenance_period.value, "start_date", null)
+        time       = lookup(deny_maintenance_period.value, "time", null)
+      }
     }
     dynamic "ip_configuration" {
       for_each = [local.ip_configurations[local.ip_configuration_enabled ? "enabled" : "disabled"]]
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/postgresql/main.tf
--- old/modules/postgresql/main.tf
+++ new/modules/postgresql/main.tf
@@ -80,10 +80,10 @@
     dynamic "deny_maintenance_period" {
       for_each = var.deny_maintenance_period
       content {
-        end_date   = lookup(deny_maintenance_period.value, "end_date" , null)
-        start_date = lookup(deny_maintenance_period.value, "start_date" , null)
-        time       = lookup(deny_maintenance_period.value, "time" , null)
-      } 
+        end_date   = lookup(deny_maintenance_period.value, "end_date", null)
+        start_date = lookup(deny_maintenance_period.value, "start_date", null)
+        time       = lookup(deny_maintenance_period.value, "time", null)
+      }
     }
     dynamic "ip_configuration" {
       for_each = [local.ip_configurations[local.ip_configuration_enabled ? "enabled" : "disabled"]]
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/mssql/main.tf
--- old/modules/mssql/main.tf
+++ new/modules/mssql/main.tf
@@ -75,10 +75,10 @@
     dynamic "deny_maintenance_period" {
       for_each = var.deny_maintenance_period
       content {
-        end_date   = lookup(deny_maintenance_period.value, "end_date" , null)
-        start_date = lookup(deny_maintenance_period.value, "start_date" , null)
-        time       = lookup(deny_maintenance_period.value, "time" , null)
-      } 
+        end_date   = lookup(deny_maintenance_period.value, "end_date", null)
+        start_date = lookup(deny_maintenance_period.value, "start_date", null)
+        time       = lookup(deny_maintenance_period.value, "time", null)
+      }
     }
     dynamic "ip_configuration" {
       for_each = [local.ip_configurations[local.ip_configuration_enabled ? "enabled" : "disabled"]]
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — DISMISSED** [review]
Thanks for the PR @aniketkumarj
Could you bump the min provider version throughout as it looks like this was added in [4.45](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4450-december-5-2022)

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by g-awmalik** [comment]
@aniketkumarj - can you update the min version in all modules versions.tf. Here's an [example](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/045bed1d212aeb8e7ec8bf89896c74fffec38f8a/modules/mssql/versions.tf#L23)

**Review by g-awmalik — CHANGES_REQUESTED** [review]
versions.tf should be updated to reflect the min. provider version for both GA and beta.

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./README.md:39:- [terraform-provider-google](https://github.com/terraform-providers/terraform-provider-google) plugin >= v4.45.0 
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ```

**Review by g-awmalik — APPROVED** [review]
LGTM

**Comment by g-awmalik** [comment]
@bharathkkb - I think your comment has been addressed as well but please confirm.

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./README.md:39:- [terraform-provider-google](https://github.com/terraform-providers/terraform-provider-google) plugin >= v4.45.0 
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ```

**Comment by comment-bot-dev** [comment]
@aniketkumarj
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by g-awmalik** [comment]
> @bharathkkb - I think your comment has been addressed as well but please confirm.

I've dismissed your review since you and I were both asking for the same thing and its had been addressed.

**Pull request merged**
