### PR TITLE
chore: update mysql-public int test

### PR DESCRIPTION
**Pull request by kaariger**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Looks like you will need to set https://github.com/terraform-google-modules/terraform-google-github-actions-runners/blob/210fc881e3a8ae7ab91216c5db7f2b16acbb39af/kitchen.yml#L19 to allow TF 1.0 in the newer image to work with existing tests

**Comment by comment-bot-dev** [comment]
@kaariger
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
We can also remove this https://github.com/terraform-google-modules/terraform-google-sql-db/blob/56d44d3bfcacd7715d45a060aacebd46a6835ff8/kitchen.yml#L37-L41

**Pull request merged**
