### PR TITLE
fix output refers to sensitive values

### PR DESCRIPTION
**Pull request by 6aKa**
Fix for issue https://github.com/terraform-google-modules/terraform-google-sql-db/issues/319

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@6aKa
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @6aKa. Please sign the CLA.
Also it is worth noting that this module is not meant to be directly used as the root module and it is only in root modules we need to mark outputs as sensitive. We can still accept this since we have this for the mysql.

**Comment by 6aKa** [comment]
I catch error when try use module from terragrunt.
```
terraform {
  source = "tfr:///GoogleCloudPlatform/sql-db/google//modules/postgresql//.?version=11.0.0"
}
inputs = {
  name                               = "test-db"
  random_instance_name = true
  ...
}
```
Because terragrunt catch all output from terraform module.

**Comment by comment-bot-dev** [comment]
@6aKa
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
