### PR TITLE
feat: Add deletion_protection.enabled for read replicas

### PR DESCRIPTION
**Pull request by zculek-fb**
Hello everyone,

At the moment, it is possible to fully protect only primary instances from accidental deletion across all surfaces (using _deletion_protection.enabled_. This addition will enable us to fully protect read replica instances as well, if needed.

### CODE REVIEW

**Comment by zculek-fb** [comment]
I do not have permissions to view why terraform-google-sql-db-int-trigger is failing:

> You do not have sufficient permissions to view this page
There was an error while loading [/cloud-build/builds/3b5adbc8-2e2d-4887-b7d7-932fe87b4976?project=2843445864](https://console.cloud.google.com/cloud-build/builds/3b5adbc8-2e2d-4887-b7d7-932fe87b4976?project=2843445864).

> The required permissions are:
Project  2843445864

> cloudbuild.builds.get

So not sure if there's anything I need to fix or it's something else.

**Comment by zculek-fb** [comment]
Thanks! Can you please let me know what the error is as well, since I don't have permissions to view? Or at least point me to how to get needed permissions, if that's possible?

**Comment by apeabody** [comment]
Hi @zculek-fb, certainly, it is:

```
Error: Error creating Database: googleapi: Error 409: Operation failed because another operation was already in progress. Try your request after the current operation is complete., operationInProgress

  with module.example.module.pg.google_sql_database.default[0],
  on ../../../modules/postgresql/main.tf line 174, in resource "google_sql_database" "default":
 174: resource "google_sql_database" "default" {
}
```

I'm re-triggering the INT test as it could be a race condition in the test.

**Comment by zculek-fb** [comment]
Thanks again Andrew

Yeah, this doesn't look related to my code addition/changes. And it seems that the re-run did the trick - the INT check is passing now.

**Review by g-awmalik — APPROVED** [review]

**Pull request merged**
