### PR TITLE
feat: Support Query Insights for MySQL for read replicas

### PR DESCRIPTION
**Pull request by smelchior**
Adds support to enable query insights for mysql read replicas

### CODE REVIEW

**Comment by smelchior** [comment]
@g-awmalik thanks for letting this run in the tests, i am not quite sure why it failed though as i can't see the logs. Is there anything I can do to make this work :)?

**Comment by g-awmalik** [comment]
> @g-awmalik thanks for letting this run in the tests, i am not quite sure why it failed though as i can't see the logs. Is there anything I can do to make this work :)?

Most likely a flaky test. I ran it again.

**Comment by smelchior** [comment]
Ah that looks better, thanks :) Any chance to get this merged?

**Review by g-awmalik — APPROVED** [review]

**Pull request merged**
