### PR TITLE
fix: to avoid password reset for existing additional users for mssql

### PR DESCRIPTION
**Pull request by Anand-chenepalli**
fix: to avoid password reset for existing additional users

### CODE REVIEW

**Comment by Anand-chenepalli** [comment]
@g-awmalik can you please run /gcbrun

**Comment by vponnam** [comment]
@g-awmalik looks like the earlier `/gcbrun` didn't actually triggered a build. Appreciate your support in reviewing this PR.

**Comment by kam1kaze** [comment]
@vponnam @g-awmalik  I've faced with the same issue but in MySQL module after upgrade from 14 to 15 major version. Should I create a new PR or we can update this one?

**Comment by Anand-chenepalli** [comment]
@kam1kaze i guess you can contribute to this PR itself

**Comment by Anand-chenepalli** [comment]
@g-awmalik Can you please trigger the /gcbrun again ?

**Comment by kam1kaze** [comment]
@Anand-chenepalli how could I do that? Just create a PR in your repo/branch (Anand-chenepalli/terraform-google-sql-db/tree/patch-2)?

**Comment by Anand-chenepalli** [comment]
@kam1kaze can you please submit  sperate pull request for your changes as there is CLA that need to be signed individually.

**Pull request merged**
