### PR TITLE
Provide an option to compress backups for PostreSQL and MySQL

### PR DESCRIPTION
**Pull request by gleichda**
The API Spec allows to compress the Backup by just adding a `.gz` to a export of type SQL

Edit: As API Activation was failing multiple times again during build. Increasing the waiting time for API Activation to 900s=15min which should bring up build success again

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@gleichda
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@gleichda
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by bharathkkb** [comment]
@gleichda We have a new option in the test framework to retry API activation errors which will be good to test if yoy have bandwidth. 
https://pkg.go.dev/github.com/GoogleCloudPlatform/cloud-foundation-toolkit/infra/blueprint-test@v0.2.0/pkg/tft#WithRetryableTerraformErrors 
https://pkg.go.dev/github.com/GoogleCloudPlatform/cloud-foundation-toolkit/infra/blueprint-test@v0.2.0/pkg/tft#pkg-variables

**Review by bharathkkb — APPROVED** [review]
Minor comments but LGTM

**Comment by comment-bot-dev** [comment]
@gleichda
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
