### PR TITLE
feat(postgres): add root password parameter

### PR DESCRIPTION
**Pull request by the-veloper**
Apparently a compliant `root_password` value is required, if there's a password policy set, due to the fact that:
```
NOTE on google_sql_database_instance:
- Second-generation instances include a default 'root'@'%' user with no password. This user will be deleted by Terraform on instance creation. You should use google_sql_user to define a custom user with a restricted host and strong password.
```

Otherwise there's the following error:
```
 Error: Error, failed to create instance postgre-dev-01: googleapi: Error 400: Invalid request: Root user's password is not policy compliant: Length of password cannot be less than 8. ., invalid
│
│   with module.postgre.google_sql_database_instance.default,
│   on .terraform/modules/postgre/modules/postgresql/main.tf line 50, in resource "google_sql_database_instance" "default":
│   50: resource "google_sql_database_instance" "default" {
```

Note source: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance
Example from google: https://cloud.google.com/sql/docs/postgres/samples/cloud-sql-postgres-instance-pvp

### CODE REVIEW

**Comment by imrannayer** [comment]
@the-veloper thanks for the PR. Lint test failed.
Thanks

**Comment by g-awmalik** [comment]
This will addres #214

**Review by g-awmalik — APPROVED** [review]

**Pull request merged**
