### PR TITLE
Support Query Insights for MySQL

### PR DESCRIPTION
**Pull request by thealgirdas**
Issue https://github.com/terraform-google-modules/terraform-google-sql-db/issues/347

GCP now support Query Insights for MySQL

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@thealgirdas
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/mysql/README.md /tmp/tmp.qqdEYhcmri/generate_docs/workspace/modules/mysql/README.md
30c30
< | insights\_config | The insights_config settings for the database. | object | `"null"` | no |
---
> | insights\_config | The insights\_config settings for the database. | <pre>object({<br>    query_string_length     = number<br>    record_application_tags = bool<br>    record_client_address   = bool<br>  })</pre> | `null` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@thealgirdas
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by thealgirdas** [comment]
@bharathkkb please review when ready! This resolves https://github.com/terraform-google-modules/terraform-google-sql-db/issues/347

**Comment by alexrjones** [comment]
@thealgirdas 
Would you be able to add support for the `safer_mysql` module? Should just require exposing the `insights_config` variable in `safer_mysql/variables.tf` and passing it to the `mysql` module in `safer_mysql/main.tf`. Otherwise I will do this in a separate PR.

**Comment by comment-bot-dev** [comment]
@thealgirdas
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/safer_mysql/README.md /tmp/tmp.WnA9Xs3JYP/generate_docs/workspace/modules/safer_mysql/README.md
186a187
> | insights\_config | The insights\_config settings for the database. | <pre>object({<br>    query_string_length     = number<br>    record_application_tags = bool<br>    record_client_address   = bool<br>  })</pre> | `null` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@thealgirdas
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@thealgirdas
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @thealgirdas

**Pull request merged**
