### PR TITLE
fix: mark replicas_instance_server_ca_certs output as sensitive

### PR DESCRIPTION
**Pull request by aghassabian**
It should fix error for server ca cert coming from this change on google provider 5.12 and later: https://github.com/hashicorp/terraform-provider-google/pull/16932

### CODE REVIEW

**Comment by aghassabian** [comment]
@imrannayer same issue for Postgressql module. Do you prefer to update this pull request or open a new one?

**Comment by imrannayer** [comment]
@aghassabian go ahead and add it in this PR

**Comment by aghassabian** [comment]
> @aghassabian go ahead and add it in this PR

@imrannayer  Done. Seems your action is required.

**Comment by aghassabian** [comment]
@imrannayer Any update on this one? It's a blocker for me.

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
