### PR TITLE
feat: adding data_cache_config to postgresql module

### PR DESCRIPTION
**Pull request by nityanavali1**

### CODE REVIEW

**Comment by nityanavali1** [comment]
PR is ready to be merge. Need Approval

**Comment by imrannayer** [comment]
Waiting for PR #523 to merge.

**Comment by imrannayer** [comment]
@nityanavali1 according to [documentation](https://cloud.google.com/sql/docs/mysql/data-cache) this feature is only available for mysql. 

[data_cache_enabled](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#data_cache_enabled) - (Optional) Whether data cache is enabled for the instance. Defaults to false Can only be used with MYSQL.

**Comment by nityanavali1** [comment]
> @nityanavali1 according to [documentation](https://cloud.google.com/sql/docs/mysql/data-cache) this feature is only available for mysql.
> 
> [data_cache_enabled](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#data_cache_enabled) - (Optional) Whether data cache is enabled for the instance. Defaults to false Can only be used with MYSQL.
- PR for updating doc is merged https://github.com/GoogleCloudPlatform/magic-modules/pull/9241 and the feature is GA available for postgres now.

**Comment by nityanavali1** [comment]
> > @nityanavali1 according to [documentation](https://cloud.google.com/sql/docs/mysql/data-cache) this feature is only available for mysql.
> > [data_cache_enabled](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#data_cache_enabled) - (Optional) Whether data cache is enabled for the instance. Defaults to false Can only be used with MYSQL.
> 
> * Documentation update is released and will take some time to reflect the changes. PR for updating terraform doc is merged [Update documentation and add test case for data cache setting as it is available for postgres now GoogleCloudPlatform/magic-modules#9241](https://github.com/GoogleCloudPlatform/magic-modules/pull/9241) and the feature is GA available for postgres now.

@imrannayer Can you approve this change based on above comments?

**Comment by imrannayer** [comment]
@nityanavali1 can you plz enable this feature in [this example](https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/examples/postgresql-public) so we can test this feature?
Also do you know why postgres page is disabled in [official doc](https://cloud.google.com/sql/docs/mysql/data-cache)

**Comment by nityanavali1** [comment]
> @nityanavali1 can you plz enable this feature in [this example](https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/examples/postgresql-public) so we can test this feature? Also do you know why postgres page is disabled in [official doc](https://cloud.google.com/sql/docs/mysql/data-cache)

The official docs will be updated on Nov 8. Although the rollout is 100% complete for this feature. As of today customers can go ahead and create postgres instances with data cache enabled https://screenshot.googleplex.com/8fvJsiEDJmQ3TWm. If the recommendation is to wait till docs update. Will do so.

 In either cases do I need to perform this
- can you plz enable this feature in [this example](https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/examples/postgresql-public) so we can test this feature?

**Comment by imrannayer** [comment]
@nityanavali1 thanks for confirming the feature. You pass the value in example as part of your PR. It will work fine during the test for your PR.

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
