### PR TITLE
Updated examples

### PR DESCRIPTION
**Pull request by konstantin-recurly**
We have implemented the `random_instance_name` variable that is optional and if it is specified it will generate a random suffix for a db name.

### CODE REVIEW

**Comment by konstantin-recurly** [comment]
@morgante not sure what is wrong with it. Please, review

**Comment by morgante** [comment]
Integration error:
```
Already have image (with digest): gcr.io/cloud-foundation-cicd/cft/developer-tools:0.4.3
Updated property [core/pass_credentials_to_gsutil].
Activated service account credentials for: [ci-account@ci-sql-db-234e.iam.gserviceaccount.com]
-----> Starting Kitchen (v1.24.0)
-----> Setting up <mssql-public-local>...
       Finished setting up <mssql-public-local> (0m0.00s).
-----> Verifying <mssql-public-local>...
$$$$$$ Running command `terraform workspace select kitchen-terraform-mssql-public-local` in directory /workspace/test/fixtures/mssql-public
$$$$$$ Running command `terraform output -json` in directory /workspace/test/fixtures/mssql-public
system: Verifying
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <mssql-public-local>.  Please see .kitchen/logs/mssql-public-local.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Linters are failing too:
```
Running terraform validate
terraform_validate ./examples/mssql-public 

Error: Reference to undeclared local value

  on outputs.tf line 22, in output "instance_name":
  22:   value = local.instance_name

A local value with the name "instance_name" has not been declared.

terraform_validate ./examples/mysql-ha 

Error: Reference to undeclared local value

  on outputs.tf line 22, in output "name":
  22:   value = local.instance_name

A local value with the name "instance_name" has not been declared.

terraform_validate ./examples/mysql-private 

Error: Reference to undeclared local value

  on outputs.tf line 23, in output "name":
  23:   value       = local.instance_name

A local value with the name "instance_name" has not been declared.

terraform_validate ./examples/mysql-public 
Success! The configuration is valid.

terraform_validate ./examples/postgresql-ha 

Error: Reference to undeclared local value

  on outputs.tf line 22, in output "name":
  22:   value = local.instance_name

A local value with the name "instance_name" has not been declared.

terraform_validate ./examples/postgresql-public 

Error: Reference to undeclared local value

  on outputs.tf line 23, in output "name":
  23:   value       = local.instance_name

A local value with the name "instance_name" has not been declared.

terraform_validate ./modules/mssql 
Success! The configuration is valid.

terraform_validate ./modules/mysql 
Success! The configuration is valid.

terraform_validate ./modules/postgresql 
Success! The configuration is valid.

terraform_validate ./modules/private_service_access 
Success! The configuration is valid.

terraform_validate ./modules/safer_mysql 
Success! The configuration is valid.

terraform_validate ./test/fixtures/mssql-ha 
Success! The configuration is valid.

terraform_validate ./test/fixtures/mssql-public 

Error: Reference to undeclared local value

  on ../../../examples/mssql-public/outputs.tf line 22, in output "instance_name":
  22:   value = local.instance_name

A local value with the name "instance_name" has not been declared.

terraform_validate ./test/fixtures/mysql-ha 

Error: Reference to undeclared local value

  on ../../../examples/mysql-ha/outputs.tf line 22, in output "name":
  22:   value = local.instance_name

A local value with the name "instance_name" has not been declared.

terraform_validate ./test/fixtures/mysql-private 

Error: Reference to undeclared local value

  on ../../../examples/mysql-private/outputs.tf line 23, in output "name":
  23:   value       = local.instance_name

A local value with the name "instance_name" has not been declared.

terraform_validate ./test/fixtures/mysql-public 
Success! The configuration is valid.

terraform_validate ./test/fixtures/postgresql-ha 

Error: Reference to undeclared local value

  on ../../../examples/postgresql-ha/outputs.tf line 22, in output "name":
  22:   value = local.instance_name

A local value with the name "instance_name" has not been declared.

terraform_validate ./test/fixtures/postgresql-public 

Error: Reference to undeclared local value

  on ../../../examples/postgresql-public/outputs.tf line 23, in output "name":
  23:   value       = local.instance_name

A local value with the name "instance_name" has not been declared.

terraform_validate ./test/setup 
Success! The configuration is valid.
```

**Comment by konstantin-recurly** [comment]
@morgante Would you, please, post the output from the test. Not sure what is going on.

**Comment by morgante** [comment]
@konstantin-recurly You can run the linters locally so I'd start by getting those passing - https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/CONTRIBUTING.md#linting-and-formatting

**Comment by konstantin-recurly** [comment]
This is what I see
```
Checking for documentation generation
Checking for trailing whitespace
Checking for missing newline at end of file
Running shellcheck
Checking file headers
1 files have incorrect boilerplate headers:
test/source.sh
Running flake8
Running terraform fmt
terraform fmt -diff -check=true -write=false ./examples/mssql-public
terraform fmt -diff -check=true -write=false ./examples/mysql-ha
terraform fmt -diff -check=true -write=false ./examples/mysql-private
terraform fmt -diff -check=true -write=false ./examples/mysql-public
terraform fmt -diff -check=true -write=false ./examples/postgresql-ha
terraform fmt -diff -check=true -write=false ./examples/postgresql-public
terraform fmt -diff -check=true -write=false ./modules/mssql
terraform fmt -diff -check=true -write=false ./modules/mysql
terraform fmt -diff -check=true -write=false ./modules/postgresql
terraform fmt -diff -check=true -write=false ./modules/private_service_access
terraform fmt -diff -check=true -write=false ./modules/safer_mysql
terraform fmt -diff -check=true -write=false ./test/fixtures/mssql-ha
terraform fmt -diff -check=true -write=false ./test/fixtures/mssql-public
terraform fmt -diff -check=true -write=false ./test/fixtures/mysql-ha
terraform fmt -diff -check=true -write=false ./test/fixtures/mysql-private
terraform fmt -diff -check=true -write=false ./test/fixtures/mysql-public
terraform fmt -diff -check=true -write=false ./test/fixtures/postgresql-ha
terraform fmt -diff -check=true -write=false ./test/fixtures/postgresql-public
terraform fmt -diff -check=true -write=false ./test/setup
Running terraform validate
terraform_validate ./examples/mssql-public
Success! The configuration is valid.

terraform_validate ./examples/mysql-ha
Success! The configuration is valid.

terraform_validate ./examples/mysql-private
Success! The configuration is valid.

terraform_validate ./examples/mysql-public
Success! The configuration is valid.

terraform_validate ./examples/postgresql-ha
Success! The configuration is valid.

terraform_validate ./examples/postgresql-public
Success! The configuration is valid.

terraform_validate ./modules/mssql
Success! The configuration is valid.

terraform_validate ./modules/mysql
Success! The configuration is valid.

terraform_validate ./modules/postgresql
Success! The configuration is valid.

terraform_validate ./modules/private_service_access
Success! The configuration is valid.

terraform_validate ./modules/safer_mysql
Success! The configuration is valid.

terraform_validate ./test/fixtures/mssql-ha
Success! The configuration is valid.

terraform_validate ./test/fixtures/mssql-public
Success! The configuration is valid.

terraform_validate ./test/fixtures/mysql-ha
Success! The configuration is valid.

terraform_validate ./test/fixtures/mysql-private
Success! The configuration is valid.

terraform_validate ./test/fixtures/mysql-public
Success! The configuration is valid.

terraform_validate ./test/fixtures/postgresql-ha
Success! The configuration is valid.

terraform_validate ./test/fixtures/postgresql-public
Success! The configuration is valid.

terraform_validate ./test/setup
Success! The configuration is valid.

Error: The following tests have failed: check_headers
make: *** [docker_test_lint] Error 1
```
Not sure what `check_headers` is.

**Comment by morgante** [comment]
@konstantin-recurly Can you resolve conflicts?

**Pull request merged**
