### PR TITLE
feat!: adds settings.deletion_protection_enabled to modules

### PR DESCRIPTION
**Pull request by KelvinVenancio**
Team,

The new provider version [4.48.0](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4480-january-9-2023) introduced a new feature `deletion_protection_enabled` to guard against deletion from all surfaces. We would like to use this feature together with the existing `deletion_protection` that already blocks deletion via Terraform.

Until version 4.47.0, we activated this option manually and since it didn't exist in the provider, it didn't drift. Today, we have more than 50 database instances between MySQL and PostgreSQL alarming drift due to this feature of the provider. This PR corrects and resolves this issue.

We appreciate if this can make it into the 14.0.0 release that will be released (if there are no errors and/or considerations in this PR, of course.).

Thanks.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@KelvinVenancio
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @KelvinVenancio!

Please increase the relevant provider versions to >= 4.48.0 for the new capability as well.  For example: https://github.com/terraform-google-modules/terraform-google-sql-db/blob/55f4206e6fbb4f1d241a12563b6296166b895833/modules/mysql/versions.tf#L30

**Comment by KelvinVenancio** [comment]
Hi @apeabody, you're welcome. Sorry, completely forgot, my mistake. I have fixed it now. Thank you.

**Comment by comment-bot-dev** [comment]
@KelvinVenancio
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by apeabody — APPROVED** [review]

**Comment by comment-bot-dev** [comment]
@KelvinVenancio
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
