### PR TITLE
fix: Acknowlege sensitive outputs for postgresql

### PR DESCRIPTION
**Pull request by pmyjavec**
Fixes an issue in which psql wouldn't provision due to the the lack of sensitive
output acknowledgement.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by morgante — APPROVED** [review]

**Comment by pmyjavec** [comment]
Hm, something unsuual happening here, my version seems very current:

```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.2.1
```

**Comment by morgante** [comment]
What's your Terraform config?

**Comment by pmyjavec** [comment]
Hey I’m using Terragrunt so that might be doing something different. I can try extract it but AFAIK it’s just a regular module declaration.

**Comment by morgante** [comment]
Got it. This is a terragrunt issue: https://github.com/gruntwork-io/terragrunt/issues/1808

**Pull request closed without merging**
