### PR TITLE
fix: Postgresql availability type shouldn't prevent backup configuration

### LINKED ISSUE #351: Postgresql availability type shouldn't prevent backup configuration
### TL;DR

If I have an availability type REGIONAL, I should be able to disable point in time recovery and backups.

### Expected behavior

* Backups disabled
* Point int time recovery disabled

### Observed behavior

* Backups enabled
* Point int time recovery enabled

### Terraform Configuration

```hcl
module "pg" {
  source               = "./modules/postgresql"
  name                 = "mydb"
  project_id           = "myproject"
  availability_type    = "REGIONAL"
  backup_configuration = {
    enabled                        = false
    start_time                     = "20:55"
    location                       = null
    point_in_time_recovery_enabled = false
    transaction_log_retention_days = null
    retained_backups               = 365
    retention_unit                 = "COUNT"
  }
}
```

### Terraform Version

```sh
Terraform v1.3.0
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by saez0pub**
The old behaviour is still preserved but we are now able to configure some backup options.

fixes #351

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@saez0pub
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @saez0pub

**Comment by comment-bot-dev** [comment]
@saez0pub
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@saez0pub
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
