### PR TITLE
fix: Add sensitive flag for MySQL module outputs

### PR DESCRIPTION
**Pull request by artemvovk**
running terraform plan on MySQL module was generating errors
because the values in these outputs are considered sensitive.

## After:
Screen Shot 2022-05-20 at 09 42 05

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@artemvovk
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by Tensho** [comment]
Relevant for me with Terraform 1.1.6 on board. Would be nice to have this merged ASAP 👍

**Comment by Tensho** [comment]
Seems like it's already in [10.0.2](https://github.com/terraform-google-modules/terraform-google-sql-db/pull/295/files) but pending release.

**Review by Tensho — APPROVED** [review]

**Review by bharathkkb — APPROVED** [review]

**Comment by comment-bot-dev** [comment]
@artemvovk
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@artemvovk
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by Tensho** [comment]
Any movement with this, ladies and gentelmen?

**Pull request merged**
