### PR TITLE
feat: add connector params timeout and export from replica

### PR DESCRIPTION
**Pull request by adeusmondo**
This PR is to add two features:

- Enable the export module to run on replica instance.
- Add connection parameter to set timeout in workflow, if the process takes more then 1800s (default value).

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@adeusmondo
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@adeusmondo
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@adeusmondo
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@adeusmondo
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@adeusmondo
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@adeusmondo
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by g-awmalik** [comment]
@adeusmondo - thanks for the PR. Can you please resolve the conflicts with master?

**Review by g-awmalik — APPROVED** [review]

**Pull request merged**
