### PR TITLE
Add sensitive flag for two outputs

### PR DESCRIPTION
**Pull request by hjoh95**
Running a terraform plan using the postgresql module resulted in two errors for these outputs. I believe this is the expected fix

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@hjoh95
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by morgante** [comment]
This is technically not required, because this module is not meant as a root module, but we can add it anyways.

**Review by morgante — APPROVED** [review]

**Comment by PhilBrammer** [comment]
Isn't this a breaking change, @morgante?  I'm assuming that there are implementations that automate/screen against TF APPLY output.

**Comment by morgante** [comment]
@PhilBrammer I wouldn't consider a sensitive flag a breaking change. It shouldn't impact any automated configuration to switch an output to sensitive, since Terraform can still reference sensitive outputs.

**Comment by PhilBrammer** [comment]
Not directly.  Working with @hjoh95 on this, but seems to me if I were using this module, I would've been getting a list of instances created as output.  Now those would be omitted, correct?  And to me, that seems like a breaking change for any consumer expecting this output.  Sure they can adapt, but am wondering if this approach is safe "just pushing through" when these modules were being used in the wrong way anyhow?  @hjoh95 created a wrapper to use this module correctly.

**Pull request merged**
